# -*- coding: utf-8 -*-
"""IntrusionProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DCunai9Zyys2zLo8jHRpHDwCImxrlu-P
"""

!pip install sdv -q

# ================================================================
#  INTRUSION DETECTION SYSTEM
#  CTGAN-Augmented Balancing + 1D-CNN Deep Learning
#  Datasets : NSL-KDD + UNSW-NB15
#  Platform : Google Colab
# ================================================================
#
#  STEP 1 — Run this once to install dependencies:
#  !pip install sdv scikit-learn tensorflow pandas numpy matplotlib seaborn joblib -q
#
#  STEP 2 — Upload your 4 CSV files when prompted:
#  - NSL_KDD_Train.csv
#  - NSL_KDD_Test.csv
#  - UNSW_NB15_training-set.csv
#  - UNSW_NB15_testing-set.csv
#
#  STEP 3 — Run this script. Everything is saved to Google Drive.
#  Future runs load from Drive cache — no re-upload, no retraining.
#
# ================================================================

import os, time, warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import joblib

from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    classification_report, confusion_matrix,
    roc_auc_score, roc_curve,
    accuracy_score, f1_score,
    precision_score, recall_score
)
from sklearn.utils.class_weight import compute_class_weight

import tensorflow as tf
from tensorflow.keras import layers, models, callbacks

from sdv.single_table import CTGANSynthesizer
from sdv.metadata import SingleTableMetadata

# ── REPRODUCIBILITY ─────────────────────────────────────────────
SEED = 42
np.random.seed(SEED)
tf.random.set_seed(SEED)

# ================================================================
#  1. GOOGLE DRIVE SETUP
# ================================================================


DRIVE_DIR = "/content/drive/MyDrive/IDS_CTGAN_DATA"
os.makedirs(DRIVE_DIR, exist_ok=True)
print(f"[✓] Drive folder ready: {DRIVE_DIR}")

# ================================================================
#  2. NSL-KDD COLUMN DEFINITIONS
# ================================================================
NSL_COLS = [
    'duration','protocol_type','service','flag','src_bytes','dst_bytes','land',
    'wrong_fragment','urgent','hot','num_failed_logins','logged_in',
    'num_compromised','root_shell','su_attempted','num_root','num_file_creations',
    'num_shells','num_access_files','num_outbound_cmds','is_host_login',
    'is_guest_login','count','srv_count','serror_rate','srv_serror_rate',
    'rerror_rate','srv_rerror_rate','same_srv_rate','diff_srv_rate',
    'srv_diff_host_rate','dst_host_count','dst_host_srv_count',
    'dst_host_same_srv_rate','dst_host_diff_srv_rate',
    'dst_host_same_src_port_rate','dst_host_srv_diff_host_rate',
    'dst_host_serror_rate','dst_host_srv_serror_rate',
    'dst_host_rerror_rate','dst_host_srv_rerror_rate',
    'label'
]

# ================================================================
#  3. DATA LOADERS  (cache to Drive on first run)
# ================================================================

def load_nsl_kdd():
    """Load NSL-KDD from Drive cache or from uploaded CSVs."""
    path_train = os.path.join(DRIVE_DIR, "nsl_train.csv")
    path_test  = os.path.join(DRIVE_DIR, "nsl_test.csv")

    if os.path.exists(path_train) and os.path.exists(path_test):
        print("[✓] NSL-KDD loaded from Drive cache")
        return pd.read_csv(path_train), pd.read_csv(path_test)

    print("[↓] Loading NSL-KDD from uploaded files …")
    # NSL-KDD files have no header row
    train = pd.read_csv("NSL_KDD_Train.csv", header=None, names=NSL_COLS)
    test  = pd.read_csv("NSL_KDD_Test.csv",  header=None, names=NSL_COLS)
    train.to_csv(path_train, index=False)
    test.to_csv(path_test,   index=False)
    print("[✓] NSL-KDD cached to Drive")
    return train, test


def load_unsw_nb15():
    """Load UNSW-NB15 from Drive cache or from uploaded CSVs."""
    path_train = os.path.join(DRIVE_DIR, "unsw_train.csv")
    path_test  = os.path.join(DRIVE_DIR, "unsw_test.csv")

    if os.path.exists(path_train) and os.path.exists(path_test):
        print("[✓] UNSW-NB15 loaded from Drive cache")
        train = pd.read_csv(path_train, low_memory=False)
        test  = pd.read_csv(path_test,  low_memory=False)
        return pd.concat([train, test], ignore_index=True)

    print("[↓] Loading UNSW-NB15 from uploaded files …")
    train = pd.read_csv("UNSW_NB15_training-set.csv",  low_memory=False)
    test  = pd.read_csv("UNSW_NB15_testing-set.csv",   low_memory=False)
    train.to_csv(path_train, index=False)
    test.to_csv(path_test,   index=False)
    print(f"[✓] UNSW-NB15 cached to Drive (train={len(train)}, test={len(test)})")
    return pd.concat([train, test], ignore_index=True)

# ================================================================
#  4. PREPROCESSING
# ================================================================

def preprocess_nsl(train_df, test_df):
    """Merge, encode, and return X, y for NSL-KDD (binary)."""
    df = pd.concat([train_df, test_df], ignore_index=True)

    # Assign column names if file was loaded without header
    if df.columns[0] != 'duration':
        df.columns = NSL_COLS

    # Drop difficulty column if present
    df.drop(columns=['difficulty'], inplace=True, errors='ignore')

    # Binary label: normal=0, attack=1
    df['label'] = df['label'].apply(
        lambda x: 0 if str(x).strip().lower() == 'normal' else 1
    )

    # Encode categorical columns
    cat_cols = ['protocol_type', 'service', 'flag']
    for col in cat_cols:
        le = LabelEncoder()
        df[col] = le.fit_transform(df[col].astype(str))

    df.replace([np.inf, -np.inf], np.nan, inplace=True)
    df.fillna(0, inplace=True)

    X = df.drop('label', axis=1).values.astype(np.float32)
    y = df['label'].values.astype(int)
    return X, y


def preprocess_unsw(df):
    """Clean, encode, and return X, y for UNSW-NB15 (binary)."""
    df = df.copy()

    # Drop non-feature columns
    drop_cols = ['id', 'attack_cat', 'srcip', 'dstip', 'Stime', 'Ltime']
    df.drop(columns=[c for c in drop_cols if c in df.columns], inplace=True)

    # Detect label column (could be 'label' or 'Label')
    label_col = next((c for c in df.columns if c.lower() == 'label'), None)
    if label_col is None:
        raise ValueError("Label column not found in UNSW-NB15 dataset!")

    # Binary label
    df[label_col] = pd.to_numeric(df[label_col], errors='coerce').fillna(0).astype(int)
    df[label_col] = df[label_col].apply(lambda x: 0 if x == 0 else 1)

    # Encode remaining object columns
    for col in df.select_dtypes(include='object').columns:
        le = LabelEncoder()
        df[col] = le.fit_transform(df[col].astype(str))

    df.replace([np.inf, -np.inf], np.nan, inplace=True)
    df.fillna(0, inplace=True)

    X = df.drop(label_col, axis=1).values.astype(np.float32)
    y = df[label_col].values.astype(int)
    return X, y

# ================================================================
#  5. CTGAN BALANCING
# ================================================================

def ctgan_balance(X, y, dataset_name, n_aug_samples=5000):
    """
    Balance minority class using CTGAN synthetic data generation.
    Saves augmented dataset to Drive — skips on subsequent runs.
    """
    aug_path = os.path.join(DRIVE_DIR, f"{dataset_name}_ctgan_augmented.csv")

    if os.path.exists(aug_path):
        print(f"[✓] CTGAN augmented data for {dataset_name} loaded from Drive")
        aug = pd.read_csv(aug_path)
        X_aug = aug.drop('label', axis=1).values.astype(np.float32)
        y_aug = aug['label'].values.astype(int)
        return X_aug, y_aug

    print(f"\n[CTGAN] Generating synthetic minority samples for {dataset_name} …")
    unique, counts = np.unique(y, return_counts=True)
    minority_class = unique[np.argmin(counts)]
    majority_class = unique[np.argmax(counts)]

    print(f"  Class distribution — {dict(zip(unique, counts))}")
    print(f"  Minority class: {minority_class} ({counts.min()} samples)")

    minority_idx = np.where(y == minority_class)[0]
    X_min = X[minority_idx]

    # Cap at 3000 samples for faster CTGAN training
    sample_size = min(len(X_min), 3000)
    X_sample = X_min[:sample_size]

    feat_cols = [f"f{i}" for i in range(X_sample.shape[1])]
    df_min = pd.DataFrame(X_sample, columns=feat_cols)
    df_min['label'] = minority_class

    metadata = SingleTableMetadata()
    metadata.detect_from_dataframe(df_min)

    synthesizer = CTGANSynthesizer(metadata, epochs=100, verbose=True)
    synthesizer.fit(df_min)
    synthetic = synthesizer.sample(num_rows=n_aug_samples)
    synthetic['label'] = minority_class

    # Combine original + synthetic
    df_orig = pd.DataFrame(X, columns=feat_cols)
    df_orig['label'] = y
    df_combined = pd.concat([df_orig, synthetic], ignore_index=True)
    df_combined.to_csv(aug_path, index=False)

    print(f"[✓] Augmented dataset saved → {aug_path}")
    new_counts = df_combined['label'].value_counts().to_dict()
    print(f"  New class distribution: {new_counts}")

    X_aug = df_combined.drop('label', axis=1).values.astype(np.float32)
    y_aug = df_combined['label'].values.astype(int)
    return X_aug, y_aug

# ================================================================
#  6. CNN MODEL DEFINITION
# ================================================================

def build_cnn(input_dim, num_classes=2):
    """
    1D-CNN for tabular intrusion detection data.
    Architecture: 3x Conv blocks → GlobalAvgPool → Dense → Softmax
    """
    inp = layers.Input(shape=(input_dim, 1))

    # Block 1
    x = layers.Conv1D(64, 3, padding='same')(inp)
    x = layers.BatchNormalization()(x)
    x = layers.Activation('relu')(x)
    x = layers.MaxPooling1D(2)(x)
    x = layers.Dropout(0.3)(x)

    # Block 2
    x = layers.Conv1D(128, 3, padding='same')(x)
    x = layers.BatchNormalization()(x)
    x = layers.Activation('relu')(x)
    x = layers.MaxPooling1D(2)(x)
    x = layers.Dropout(0.3)(x)

    # Block 3
    x = layers.Conv1D(256, 3, padding='same')(x)
    x = layers.BatchNormalization()(x)
    x = layers.Activation('relu')(x)
    x = layers.GlobalAveragePooling1D()(x)
    x = layers.Dropout(0.4)(x)

    # Classifier head
    x = layers.Dense(128, activation='relu')(x)
    x = layers.Dropout(0.3)(x)
    out = layers.Dense(num_classes, activation='softmax')(x)

    model = models.Model(inp, out)
    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )
    return model

# ================================================================
#  7. TRAINING & EVALUATION
# ================================================================

def train_evaluate(X, y, dataset_name, epochs=30, batch_size=256):
    """
    Full training pipeline with evaluation and plots.
    Best model is saved to Drive automatically.
    """
    print(f"\n{'='*58}")
    print(f"  TRAINING: {dataset_name}")
    print(f"{'='*58}")

    # Scale features
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    # Save scaler for inference
    scaler_path = os.path.join(DRIVE_DIR, f"{dataset_name}_scaler.pkl")
    joblib.dump(scaler, scaler_path)

    # Train/test split
    X_train, X_test, y_train, y_test = train_test_split(
        X_scaled, y, test_size=0.2, random_state=SEED, stratify=y
    )

    # Reshape for CNN: (samples, features, 1)
    X_train_cnn = X_train[..., np.newaxis]
    X_test_cnn  = X_test[..., np.newaxis]

    # Class weights for any residual imbalance
    cw = compute_class_weight('balanced', classes=np.unique(y_train), y=y_train)
    class_weight = dict(enumerate(cw))
    print(f"  Class weights: {class_weight}")

    # Build model
    model = build_cnn(input_dim=X_train_cnn.shape[1])
    model.summary()

    # Callbacks
    model_path = os.path.join(DRIVE_DIR, f"{dataset_name}_cnn_best.keras")
    cb_list = [
        callbacks.ModelCheckpoint(
            model_path, save_best_only=True,
            monitor='val_accuracy', verbose=1
        ),
        callbacks.EarlyStopping(
            patience=7, restore_best_weights=True,
            monitor='val_loss', verbose=1
        ),
        callbacks.ReduceLROnPlateau(
            patience=3, factor=0.5, min_lr=1e-6, verbose=1
        )
    ]

    # Train
    t0 = time.time()
    history = model.fit(
        X_train_cnn, y_train,
        validation_split=0.15,
        epochs=epochs,
        batch_size=batch_size,
        class_weight=class_weight,
        callbacks=cb_list,
        verbose=1
    )
    elapsed = time.time() - t0
    print(f"\n[✓] Training completed in {elapsed:.1f}s")

    # ── PREDICTIONS ──────────────────────────────────────────
    y_pred_prob = model.predict(X_test_cnn, verbose=0)
    y_pred      = np.argmax(y_pred_prob, axis=1)

    # ── METRICS ──────────────────────────────────────────────
    acc  = accuracy_score(y_test, y_pred)
    f1   = f1_score(y_test, y_pred, average='weighted')
    prec = precision_score(y_test, y_pred, average='weighted', zero_division=0)
    rec  = recall_score(y_test, y_pred, average='weighted')
    auc  = roc_auc_score(y_test, y_pred_prob[:, 1]) \
           if len(np.unique(y_test)) == 2 else None

    print(f"\n{'─'*40}")
    print(f"  {dataset_name} — Final Results")
    print(f"{'─'*40}")
    print(f"  Accuracy  : {acc:.4f}  ({acc*100:.2f}%)")
    print(f"  F1-Score  : {f1:.4f}")
    print(f"  Precision : {prec:.4f}")
    print(f"  Recall    : {rec:.4f}")
    if auc:
        print(f"  ROC-AUC   : {auc:.4f}")
    print(f"{'─'*40}")
    print(classification_report(
        y_test, y_pred,
        target_names=['Normal', 'Attack'],
        digits=4
    ))

    # ── PLOT 1: Training curves + Confusion Matrix ────────────
    fig, axes = plt.subplots(1, 3, figsize=(20, 5))
    fig.suptitle(f"{dataset_name}  |  CNN Evaluation", fontsize=15, fontweight='bold')

    # Accuracy curve
    axes[0].plot(history.history['accuracy'],     label='Train', linewidth=2)
    axes[0].plot(history.history['val_accuracy'], label='Val',   linewidth=2)
    axes[0].set_title('Accuracy', fontsize=12)
    axes[0].set_xlabel('Epoch'); axes[0].set_ylabel('Accuracy')
    axes[0].legend(); axes[0].grid(True, alpha=0.3)

    # Loss curve
    axes[1].plot(history.history['loss'],     label='Train', linewidth=2, color='tomato')
    axes[1].plot(history.history['val_loss'], label='Val',   linewidth=2, color='coral')
    axes[1].set_title('Loss', fontsize=12)
    axes[1].set_xlabel('Epoch'); axes[1].set_ylabel('Loss')
    axes[1].legend(); axes[1].grid(True, alpha=0.3)

    # Confusion Matrix
    cm = confusion_matrix(y_test, y_pred)
    sns.heatmap(
        cm, annot=True, fmt='d', cmap='Blues', ax=axes[2],
        xticklabels=['Normal', 'Attack'],
        yticklabels=['Normal', 'Attack'],
        linewidths=0.5
    )
    axes[2].set_title('Confusion Matrix', fontsize=12)
    axes[2].set_ylabel('True Label')
    axes[2].set_xlabel('Predicted Label')

    plt.tight_layout()
    plot_path = os.path.join(DRIVE_DIR, f"{dataset_name}_evaluation.png")
    plt.savefig(plot_path, dpi=150, bbox_inches='tight')
    plt.show()
    print(f"[✓] Evaluation plot saved → {plot_path}")

    # ── PLOT 2: ROC Curve ─────────────────────────────────────
    if auc:
        fpr, tpr, _ = roc_curve(y_test, y_pred_prob[:, 1])
        plt.figure(figsize=(6, 5))
        plt.plot(fpr, tpr, color='darkorange', linewidth=2,
                 label=f'ROC Curve (AUC = {auc:.4f})')
        plt.plot([0, 1], [0, 1], 'k--', linewidth=1)
        plt.fill_between(fpr, tpr, alpha=0.1, color='darkorange')
        plt.title(f'{dataset_name} — ROC Curve', fontsize=13)
        plt.xlabel('False Positive Rate')
        plt.ylabel('True Positive Rate')
        plt.legend(loc='lower right')
        plt.grid(True, alpha=0.3)
        roc_path = os.path.join(DRIVE_DIR, f"{dataset_name}_roc.png")
        plt.savefig(roc_path, dpi=150, bbox_inches='tight')
        plt.show()
        print(f"[✓] ROC curve saved → {roc_path}")

    return model, scaler, history

# ================================================================
#  8. FAST INFERENCE  (load saved model, no retraining)
# ================================================================

def load_and_predict(dataset_name, X_new):
    """
    Load best saved model + scaler from Drive and run inference.

    Usage:
        X_new  = raw (unscaled) feature array, shape (n_samples, n_features)
        preds  = load_and_predict("NSL_KDD", X_new)
        # preds: array of 0 (Normal) or 1 (Attack)
    """
    model_path  = os.path.join(DRIVE_DIR, f"{dataset_name}_cnn_best.keras")
    scaler_path = os.path.join(DRIVE_DIR, f"{dataset_name}_scaler.pkl")

    if not os.path.exists(model_path):
        raise FileNotFoundError(f"No saved model found for {dataset_name}. Train first.")

    model  = tf.keras.models.load_model(model_path)
    scaler = joblib.load(scaler_path)

    X_scaled = scaler.transform(X_new)[..., np.newaxis]
    probs    = model.predict(X_scaled, verbose=0)
    preds    = np.argmax(probs, axis=1)
    return preds  # 0 = Normal, 1 = Attack

# ================================================================
#  9. MAIN PIPELINE
# ================================================================

if __name__ == "__main__":

    # ── UPLOAD FILES (runs once, then cached to Drive) ────────
    from google.colab import files
    print("\n[!] Please upload your 4 CSV files:")
    print("    NSL_KDD_Train.csv, NSL_KDD_Test.csv,")
    print("    UNSW_NB15_training-set.csv, UNSW_NB15_testing-set.csv\n")
    uploaded = files.upload()

    # ── NSL-KDD PIPELINE ──────────────────────────────────────
    print("\n" + "="*58)
    print("  DATASET 1: NSL-KDD")
    print("="*58)

    nsl_train, nsl_test = load_nsl_kdd()
    X_nsl, y_nsl = preprocess_nsl(nsl_train, nsl_test)
    print(f"Raw shape     : {X_nsl.shape}")
    print(f"Class dist    : Normal={np.sum(y_nsl==0)}, Attack={np.sum(y_nsl==1)}")

    X_nsl_aug, y_nsl_aug = ctgan_balance(X_nsl, y_nsl, "NSL_KDD", n_aug_samples=5000)
    print(f"After CTGAN   : {X_nsl_aug.shape}")
    print(f"Class dist    : Normal={np.sum(y_nsl_aug==0)}, Attack={np.sum(y_nsl_aug==1)}")

    nsl_model, nsl_scaler, nsl_hist = train_evaluate(
        X_nsl_aug, y_nsl_aug, "NSL_KDD", epochs=30, batch_size=256
    )

    # ── UNSW-NB15 PIPELINE ────────────────────────────────────
    print("\n" + "="*58)
    print("  DATASET 2: UNSW-NB15")
    print("="*58)

    unsw_df = load_unsw_nb15()
    X_unsw, y_unsw = preprocess_unsw(unsw_df)
    print(f"Raw shape     : {X_unsw.shape}")
    print(f"Class dist    : Normal={np.sum(y_unsw==0)}, Attack={np.sum(y_unsw==1)}")

    X_unsw_aug, y_unsw_aug = ctgan_balance(X_unsw, y_unsw, "UNSW_NB15", n_aug_samples=5000)
    print(f"After CTGAN   : {X_unsw_aug.shape}")
    print(f"Class dist    : Normal={np.sum(y_unsw_aug==0)}, Attack={np.sum(y_unsw_aug==1)}")

    unsw_model, unsw_scaler, unsw_hist = train_evaluate(
        X_unsw_aug, y_unsw_aug, "UNSW_NB15", epochs=30, batch_size=256
    )

    # ── DONE ──────────────────────────────────────────────────
    print("\n" + "="*58)
    print("  ✓ PIPELINE COMPLETE")
    print(f"  All files saved to: {DRIVE_DIR}")
    print("="*58)
    print("""
  Files saved to Drive:
  ├── nsl_train.csv / nsl_test.csv
  ├── unsw_train.csv / unsw_test.csv
  ├── NSL_KDD_ctgan_augmented.csv
  ├── UNSW_NB15_ctgan_augmented.csv
  ├── NSL_KDD_cnn_best.keras
  ├── UNSW_NB15_cnn_best.keras
  ├── NSL_KDD_scaler.pkl
  ├── UNSW_NB15_scaler.pkl
  ├── NSL_KDD_evaluation.png + roc.png
  └── UNSW_NB15_evaluation.png + roc.png

  FAST INFERENCE (future runs — no retraining needed):
  ────────────────────────────────────────────────────
  from IDS_CTGAN_CNN_v2 import load_and_predict
  preds = load_and_predict("NSL_KDD",  X_new)
  preds = load_and_predict("UNSW_NB15", X_new)
  # 0 = Normal  |  1 = Attack
    """)

